In [1]:
import numpy as np

In [4]:
lista = [1,2,3,4,5,6,7,8,9]

In [6]:
arr = np.array(lista)

In [8]:
type(arr)

numpy.ndarray

In [11]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexing

In [16]:
arr[0]

1

In [20]:
matriz[0] # Con esto ingresamos a la primera fila

array([1, 2, 3])

In [23]:
# Con estos ingresamos a una ubicación en especifico
matriz[0][2]
matriz[0,2]

3

# Slicing

Trae un rango de valores

In [25]:
arr[0:3]

array([1, 2, 3])

In [26]:
arr[::3] # Leer todo el array pero de 3 en 3

array([1, 4, 7])

In [28]:
arr[-3:] # Obtener los ultimos 3 valores

array([7, 8, 9])

In [29]:
matriz[1:,0:2] # Leer a partir de la 2da fila y las 2 primeras columnas

array([[4, 5],
       [7, 8]])