In [2]:
import numpy as np

In [5]:
scalar = np.array(42)
print(scalar)
scalar.ndim

#Un escalar es de dimensión 0.

42


0

In [7]:
vector = np.array([0,1,2])
print(vector)
vector.ndim

#Un vesctor es de dimensión 1.

[0 1 2]


1

In [11]:
matriz = np.array([[0,1,2], [4,5,6]])
print(matriz)
matriz.ndim

#Una matriz es de dimensión 2.

[[0 1 2]
 [4 5 6]]


2

In [14]:
tensor = np.array([[[0,1,2], [4,5,6]], [[0,1,2], [4,5,6]]]) # Le agregamos una nueva dimension a la tensor
print(tensor)
tensor.ndim

#Un tensor es de dimensión 3 (en este caso).

[[[0 1 2]
  [4 5 6]]

 [[0 1 2]
  [4 5 6]]]


3

## Agregar o eliminar dimensiones

In [17]:
# Vcetor con 10 dimensiones

vector = np.array([0,1,2], ndmin=10)
print(vector)
vector.ndim

print(f"un vector {vector} es de dimensión {vector.ndim}")

[[[[[[[[[[0 1 2]]]]]]]]]]
un vector [[[[[[[[[[0 1 2]]]]]]]]]] es de dimensión 10


In [23]:
# Expandir dimendiones

expand = np.expand_dims(np.array([0,1,2,3]), axis = 0)

print(f"expand tiene {expand.ndim} dimensiones")

expand tiene 2 dimensiones


In [26]:
# Eliminar dimendiones

print(vector, vector.ndim)

vector2 = np.squeeze(vector)

print(vector2, vector2.ndim)

# Con esto comprimimos en la dimensión correcta.

[[[[[[[[[[0 1 2]]]]]]]]]] 10
[0 1 2] 1
