In [2]:
import numpy as np

In [4]:
np.arange(0,20)  # Crear arrays con un rango

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.zeros(3) # Esto se usa mucho en DataScience

array([0., 0., 0.])

In [8]:
np.zeros((10,10))  # Esto sirve para definir estructuras

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.linspace(0,10,100) # Generar datos normalizados entre 0 y 10

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.eye(4) # Crear matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(4,4) # Crear valores aleatorios entre 0 y 1

array([[0.16160794, 0.24115895, 0.67245456, 0.07528452],
       [0.18190666, 0.21018065, 0.88946675, 0.15718047],
       [0.08889036, 0.1917152 , 0.77615171, 0.0074152 ],
       [0.94895613, 0.46778053, 0.30489231, 0.85698181]])

In [19]:
np.random.randint(1,51) # Generar un entero aleatorio

21

In [20]:
np.random.randint(1, 100, (10,10)) # Generar enteros entre 1 y 100 en una matriz 10X10

array([[48, 10, 99, 58, 79, 26,  6, 45, 51, 48],
       [33, 81, 14, 36, 21, 79, 88, 64, 61, 49],
       [52,  1, 34,  5, 82, 62, 54, 11, 40, 81],
       [51, 57,  9, 68, 83, 45, 86, 13, 85, 17],
       [59, 84, 49, 66, 73, 71, 72, 13, 76,  6],
       [58, 58, 51, 96, 80, 32, 45, 90, 72, 30],
       [23, 77, 13, 28, 59, 45, 17, 53, 48, 12],
       [74, 38, 34, 44, 68,  9,  2, 40, 82, 53],
       [46, 78, 91, 57, 14, 12, 77, 65, 25, 17],
       [98, 80, 54, 38, 79, 28, 18, 30, 33,  3]])