In [2]:
import numpy as np

In [5]:
arr = np.random.randint(1,10,(3,2))

In [7]:
arr.shape # Shape dice cuantas dimensiones tiene el array

(3, 2)

In [9]:
arr

array([[1, 8],
       [9, 8],
       [1, 9]])

In [10]:
arr.reshape(1,6) # Cambiarle la forma de 3X2 a 1X6

array([[1, 8, 9, 8, 1, 9]])

In [12]:
arr.reshape(2,3)

array([[1, 8, 9],
       [8, 1, 9]])

In [14]:
np.reshape(arr, (1,6)) # Esto es lo mismo que reshape

array([[1, 8, 9, 8, 1, 9]])

In [16]:
#Reordenar por filas

np.reshape(arr, (2,3), 'C')

# Este es el más recomendado, lo hace en lenguaje C

array([[1, 8, 9],
       [8, 1, 9]])

In [18]:
# Reordenar por columnas

np.reshape(arr, (2,3), 'F')

# Este no es tan recomendado, lo hace en lenguaje Fortrand

array([[1, 1, 8],
       [9, 8, 9]])

In [19]:
#Ordenar según el almacenamiento en mi sistema 

np.reshape(arr, (2,3), 'A')

array([[1, 8, 9],
       [8, 1, 9]])