In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20, 10)

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[18, 14, 15,  3,  3],
       [10,  2,  8, 19, 19]])

In [5]:
arr.max() # Con esto traemos el numero mas grande del array
matriz.max()

19

In [6]:
matriz.max(0) # Obtener el valor más grande cada fila

array([18, 14, 15, 19, 19])

In [7]:
arr.argmax() # Obtener el indice de donde esta el valor mas grande

8

In [9]:
arr.min() # Valor mas pequeño del array

2

In [10]:
arr

array([18, 14, 15,  3,  3, 10,  2,  8, 19, 19])

In [12]:
arr.ptp() #Trae la distancia entre el valor más pequeño y el más grande del array, es como el rango.

17

In [14]:
np.percentile(arr, 50) # Obtener percentil 50

12.0

In [15]:
arr.sort() # Ordenar de menor a mayor

In [17]:
np.median(arr) # Obtener la mediana

12.0

In [19]:
np.median(matriz, 0) # Mediana de cada fila de la matriz

array([ 8. ,  9. , 10.5, 13.5, 14.5])

In [21]:
np.std(arr) #Desviación Estándar

6.487680633323438

In [23]:
np.var(arr) # Varianza

42.09

In [25]:
np.mean(arr) # Promedio

11.1

In [34]:
a = np.array([[1,2], [3,4]])
b = np.array([5,6])

"""
np.concatenate((a,b), axis = 0) # Concatenar en una tupla

Esto arroja error por que las dimensiones de los arrays no coinciden (algebra matricial)
"""

In [35]:
b = np.expand_dims(b, axis = 0)

np.concatenate((a,b), axis = 0) # Concatenar en una tupla

array([[1, 2],
       [3, 4],
       [5, 6]])