In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
trozo_de_arr  = arr[0:6]

In [8]:
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [13]:
arr # Vemos que auqnue hicimos los cambios en trozo_de_arr, estos tambien se reflejaron en el original. Para evitar eso usamos copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()

In [19]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr # Vemos que con copy ya no se presenta el problema de modificar el original

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])