In [2]:
import numpy as np

In [23]:
arr = np.linspace(1, 10, 10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [10]:
Ind_cond = arr>5 # Lista booleana que guarda los resultados

In [24]:
arr[arr>5] # Trae los valores que cumplen con la concidion

array([ 6,  7,  8,  9, 10], dtype=int8)

In [25]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [27]:
arr[arr>5] = 99
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)